apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-test-app
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-test-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-test-app
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
