apiVersion: v1
kind: PersistentVolumeClaim
metdata:
  name: my-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-sc"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-sc
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: nfs
      zone: us-central-1
