apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
stringData:
  - password: samplepass

env:
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secret
        key: password

envFrom:
  - secretRef:
      name: db-secret
