apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: httpd:alpine
          ports:
            - containerPort: 80
          env:
            - name: ENV_MODE
              value: "staging"
          volumeMounts:
            - name: config-vol
              mountPath: /config
              readOnly: true
            - name: data-vol
              mountPath: /data
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "250m"
              memory: "64Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: config-vol
          configMap:
            name: app-config
        - name: data-vol
          persistantVolumeClaim:
            claimName: app-data-pvc
