apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

namePrefix: dev-
nameSuffix: ""

patches:
  - path: patch-replicas.yaml
    target:
      kind: Deployment
      name: test-app
